//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dberzervasyonTable
    {
        public int rezervasyonID { get; set; }
        public Nullable<int> seferID { get; set; }
        public Nullable<int> m_ID { get; set; }
        public Nullable<byte> kolTuknumara { get; set; }
        public Nullable<decimal> ucreT { get; set; }
        public Nullable<System.DateTime> rezervasyonTarihi { get; set; }
    
        public virtual dbmusTeriTable dbmusTeriTable { get; set; }
        public virtual dbseferTable dbseferTable { get; set; }
    }
}
