//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbkasaTable
    {
        public short ID { get; set; }
        public Nullable<decimal> Kasa { get; set; }
    }
}
