//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbmusTeriTable
    {
        public dbmusTeriTable()
        {
            this.dberzervasyonTable = new HashSet<dberzervasyonTable>();
        }
    
        public int m_ID { get; set; }
        public string m_ad { get; set; }
        public string m_soyad { get; set; }
        public Nullable<bool> cinsiyeT { get; set; }
        public Nullable<long> phone { get; set; }
        public string mail { get; set; }
        public Nullable<long> kimlikno { get; set; }
    
        public virtual ICollection<dberzervasyonTable> dberzervasyonTable { get; set; }
    }
}
