//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dboTobusTable
    {
        public dboTobusTable()
        {
            this.dbseferTable = new HashSet<dbseferTable>();
        }
    
        public int busID { get; set; }
        public string marka { get; set; }
        public string plaka { get; set; }
        public Nullable<byte> kolTuksayisi { get; set; }
    
        public virtual ICollection<dbseferTable> dbseferTable { get; set; }
    }
}
