//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbseferTable
    {
        public dbseferTable()
        {
            this.dberzervasyonTable = new HashSet<dberzervasyonTable>();
        }
    
        public int seferID { get; set; }
        public Nullable<int> busID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<System.DateTime> daTe { get; set; }
        public Nullable<decimal> fiyaT { get; set; }
    
        public virtual ICollection<dberzervasyonTable> dberzervasyonTable { get; set; }
        public virtual dboTobusTable dboTobusTable { get; set; }
        public virtual dbsehirTable dbsehirTable { get; set; }
    }
}
