//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTobüs_BileT_Rezervasyon_SiTtemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsehirTable
    {
        public dbsehirTable()
        {
            this.dbseferTable = new HashSet<dbseferTable>();
        }
    
        public int sehirID { get; set; }
        public string sehir1 { get; set; }
        public string sehir2 { get; set; }
        public Nullable<int> mesafe_KM { get; set; }
    
        public virtual ICollection<dbseferTable> dbseferTable { get; set; }
    }
}
